name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: jenil9761/homzy
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          push: true
          tags: |
            jenil9761/homzy
            jenil9761/homzy:${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Check out deployment repo
        uses: actions/checkout@v4
        with:
          repository: jenil9761/ymlfilerepo
          path: ymlfilerepo
          token: ${{ secrets.GIT_TOKEN }}

      - name: Debug - List files in ymlfilerepo
        run: ls -R ymlfilerepo

      - name: Configure Git user
        run: |
          git config --global user.email "jenill9761@gmail.com"
          git config --global user.name "jenil9761"

      - name: Update Kubernetes deployment
        run: |
          sed -i "s|image: jenil9761/homzy:.*|image: jenil9761/homzy:${{ github.run_number }}|g" ymlfilerepo/manifest/deployment.yml
          cd ymlfilerepo
          git add .
          git commit -m "Update deployment to use image jenil9761/homzy:${{ github.run_number }}"
          git push
